### Creates new Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "test doe",
  "email" : "test@example.com",
  "address" : "123 main street",
  "dateOfBirth" : "2004-05-12",
  "registeredDate" : "2025-09-28"
}

###